export const FETCH_APP_NAME_TRACKING_SUCCESS = 'FETCH_APP_NAME_TRACKING_SUCCESS'
export const SORT_APP_NAME_SUCCESS = 'SORT_APP_NAME_SUCCESS'
export const CLEAR_APP_NAME_SUCCESS = 'CLEAR_APP_NAME_SUCCESS'