inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'client/**/*'

Rails:
  Enabled: true

Style/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyleForEmptyBraces: no_space
  EnforcedStyle: no_space

Style/Documentation:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/MethodLength:
  Enabled: false