export const FETCH_CARRIER_NAME_TRACKING_SUCCESS = 'FETCH_CARRIER_NAME_TRACKING_SUCCESS'
export const SORT_CARRIER_NAME_SUCCESS = 'SORT_CARRIER_NAME_SUCCESS'
export const CLEAR_CARRIER_NAME_SUCCESS = 'CLEAR_CARRIER_NAME_SUCCESS'