export const FETCH_VAST_DATA_SUCCESS = 'FETCH_VAST_DATA_SUCCESS'
export const CREATE_VAST_SUCCESS = 'CREATE_VAST_SUCCESS'
export const LOAD_VAST_SUCCESS = 'LOAD_VAST_SUCCESS'
export const CLEAR_OLD_VAST = 'CLEAR_OLD_VAST'
