export const FETCH_NATIONALITIES_SUCCESS = 'FETCH_NATIONALITIES_SUCCESS'
export const CLEAR_NATIONALITIES = 'CLEAR_NATIONALITIES'

export const CLEAR_NATIONALITY = 'CLEAR_NATIONALITY'
export const FETCH_NATIONALITY_SUCCESS = 'FETCH_NATIONALITY_SUCCESS'
export const NEW_NATIONALITY = 'NEW_NATIONALITY'
export const NEW_NATIONALITY_SUCCESS = 'NEW_NATIONALITY_SUCCESS'
export const EDIT_NATIONALITY = 'EDIT_NATIONALITY'
